---
# * Target whatever is the default group of hosts;
# * If any errors happen in the middle, stop the
# whole execution;
# * Make sure to `become` a privileged user;
# * Gather facts about the machine (requires
# python);
# * Execute the `prometheus_node_exporter` and `docker` roles.
- hosts: nodes
  become: true
  any_errors_fatal: true
  roles:
    - docker
    - prometheus_node_exporter