---
- name: Install Prometheus Server
  hosts: 127.0.0.1
  become: true
  gather_facts: false

  tasks:

  - name: Ensure wget present
    apt:
      name: wget
      state: present

  - name: Get Prometheus package
    get_url:
      url: https://github.com/prometheus/prometheus/releases/download/v2.31.1/prometheus-2.31.1.linux-amd64.tar.gz
      dest: /tmp/

  - name: Untar archive
    unarchive:
      src: /tmp/prometheus-2.31.1.linux-amd64.tar.gz
      dest: /tmp/
    
  - name: Create prometheus user
    user:
      name: prometheus
      shell: /bin/false
      create_home: no

  - name: Create /var/lib/prometheus
    file:
      path: /var/lib/prometheus
      state: directory
      owner: prometheus
      group: prometheus

  - name: Copy prometheus exec to /usr/local/bin
    copy:
      src: /tmp/prometheus-2.31.1.linux-amd64/promtool
      dest: /usr/local/bin/
      owner: prometheus
      group: prometheus
      mode: '0755'

  - name: Copy promtool exec to /usr/local/bin
    copy:
      src: /tmp/prometheus-2.31.1.linux-amd64/prometheus
      dest: /usr/local/bin/
      owner: prometheus
      group: prometheus
      mode: '0755'

  - name: Create /etc/prometheus directory
    file:
      path: /etc/prometheus
      state: directory
      owner: prometheus
      group: prometheus

  - name: Copy Prometheus consoles to /etc/prometheus directory
    copy:
      src: /tmp/prometheus-2.31.1.linux-amd64/consoles
      dest: /etc/prometheus/
      owner: prometheus
      group: prometheus

  - name: Copy Prometheus console_libraries to /etc/prometheus directory
    copy:
      src: /tmp/prometheus-2.31.1.linux-amd64/console_libraries
      dest: /etc/prometheus/
      owner: prometheus
      group: prometheus

  - name: Copy Prometheus configuration to /etc/prometheus directory
    copy:
      src: /home/vagrant/configurations/prometheus/prometheus.yml
      dest: /etc/prometheus/
      owner: prometheus
      group: prometheus

  - name: Create a prometheus service file
    copy:
      src: /home/vagrant/configurations/prometheus/prometheus.service
      dest: /etc/systemd/system/

  - name: start the prometheus service
    systemd:
      daemon_reload: yes
      name: prometheus
      state: started
      enabled: yes
